### PR TITLE
Added open build/release in browser feature

### PR DESCRIPTION
**Pull request by myMartek**
Referring to #14 I did a pull request implementing this feature reguest.

### CODE REVIEW

**Comment by panuoksala** [comment]
I will test this in weekend and approve it if everything works.

**Comment by myMartek** [comment]
I updated my branch to resolve conflicts

**Comment by panuoksala** [comment]
OK good. The new release took all my time, so I try to check this in upcoming weekend.

**Comment by panuoksala** [comment]
Very good feature!

**Comment by coryvb123** [comment]
@panuoksala It doesn't look like this got merged into the repo before it was closed. Was this going to be added? I'd love this feature.

**Comment by panuoksala** [comment]
Yes it was merged after release. I was waiting for something else to come up, before providing new version. As now it seems that nothing is coming up in near future I could release this change alone.

**Pull request merged**
