### PR TITLE
Adding build/release image status, interval updates and long press actions

### PR DESCRIPTION
**Pull request by jernejk**
I have added several new features to the button.

- Show status for the build definition
- Support for multiple build/release definitions
- Interval status update
   - Interval 0 disables updates
- On tap and long-press action (configurable)
   - Do nothing
   - Update status (default for tap)
   - Start build/release (default for long press)
- When definition ID is empty/0
   - Show status of last running or currently in progress definition ID 
   - On run, run all of the definitions for the project

image

image

image

NOTE: I still need to fully implement release functionality but build is done.
The Release functionality should be done by the end of the week but you're welcome to review the rest (there should only be some minor changes in AzureDevOpsService).

**UPDATE:** Done, releases are included. 😊

Linked to #1

### CODE REVIEW

**Comment by jernejk** [comment]
Just a few notes on the code.

There is no `BasicAction` that gives you tap, long-press, background update, etc, so we can later add more buttons with similar functionalities.

And most of the logic is moved to a service because it required a bit more code and the original action would have a lot of code to handle all of the scenarios.

Builds do not support waiting for approval because there are no APIs.
Releases do not support waiting for approval because I don't have releases atm that have that to properly test it.

**Comment by panuoksala** [comment]
After triggering the build or release the top right icon is set to OK, should it be maybe set to in progress, because it is most likely that the pipeline is going to be in progress state?

**Comment by panuoksala** [comment]
After triggering build with long push and setting the short push to show build status. The short push always shows OK icon in top right, even though that the build is still in progress.

**Comment by jernejk** [comment]
Yeah, it shows the real status and you need to wait for a few seconds to see the build/release to be queued or in progress

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jernejk** [comment]
Tomorrow I'll set it to be waiting image so that next update will show the right status.

Any other changes needed?

**Comment by jernejk** [comment]
Done, it will show "wait" status instead of current status. :)
It's wait status (full circle) as opposed to in progress (circle with gaps) as we don't know if the build will be picked up right away or if it's going to be queued. Based on my testing, it takes ~5 seconds before Azure DevOps shows the correct status.

**Comment by panuoksala** [comment]
Sorry I didn't have yesterday more time to test, but I will test new features today and then merge if everything is ok.

**Comment by panuoksala** [comment]
One more thing. Currently the BackgroundTask is polling Azure DevOps all the time. Even though that there is no build to poll and I think that is a bit bad by design. 

I would start the BackgroundTask when build is initialized and continue polling until the build is completed. Then kill the poller. 

If two builds are initialized by pressing the button twice, then the later would be used...

**Comment by panuoksala** [comment]
Maybe just limit the minimum to 10 seconds to avoid flooding of polling actions (for example 10 buttons with 5 second interval)? What do you say?

**Comment by panuoksala** [comment]
min="10" into property_inspector.html update_status_every_second should do the trick.

**Comment by panuoksala** [comment]
I think you have done astonishing job. I will actually merge this in and fix the min value by myself.

**Comment by jernejk** [comment]
Thanks for merging the code. :)
I agree with minimum 10 seconds should be reasonable but I'm if we should limit it in case somebody really wants it. (also lots of DevOps dashboards are polling at a pretty high rate from lots of places, I wouldn't worry about it)
Also, keep in mind that 0 = no polling and we would need add a checkbox to disable background polling if we want to add this feature back.

I would be against stopping the polling because the great thing about this button is that I can see when my teammates are pushing deployments. For instance, our build is ~40 minutes and I do 10-minute polls so that I can be on top when new stuff is coming in.

That being said, I like the idea of increasing the rate of polling when a build/release is in progress.
I wonder if that should be a separate interval, though.

My a solution architect and my motivation is to build a mini dashboard of projects and I'm responsible for but not necessarily working on that day. (which is why I have created lots of "issue" features so that I don't forget what I want to implement)

My use case is more toward passive observation over running tasks but I don't want others to lose that ability, which is why I put the extra effort to accommodate both use cases. 😊

**Pull request merged**
